title: WorldMemBench
email: you@example.com
description: >
  WorldMemBench — a benchmark to evaluate the memory capabilities of learned world models.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
theme: minima
plugins:
  - jekyll-feed

markdown: kramdown

collections:
  pages:
    output: true

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: default
